import { Manrope } from "next/font/google";
import "./globals.css";
import AppProvider from "@/context/AppContext";
import { Toaster } from "react-hot-toast";
import StripeWrapper from "@/components/StripeWrapper";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ PRECONNECT (NETWORK WARNING FIX) */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${manrope.className} antialiased`}>
        <AppProvider>
          <StripeWrapper>
          {children}
          </StripeWrapper>
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3000,
            }}
          />
        </AppProvider>
      </body>
    </html>
  );
}
